components:
    examples: {}
    headers: {}
    parameters: {}
    requestBodies: {}
    responses: {}
    schemas:
        User:
            properties:
                id:
                    type: string
                name:
                    type: string
                age:
                    type: number
                    format: double
            required:
                - id
                - name
                - age
            type: object
            additionalProperties: false
        UserCreationDTO:
            properties:
                name:
                    type: string
                age:
                    type: number
                    format: double
            required:
                - name
                - age
            type: object
            additionalProperties: false
    securitySchemes:
        bearerAuth:
            type: http
            name: Authorization
            scheme: bearer
            in: header
info:
    title: inversify-tsoa
    version: 1.0.0
    license:
        name: MIT
    contact:
        name: 'Romildo Júnior '
        email: jrmmendes@outlook.com
openapi: 3.0.0
paths:
    '/users/{id}':
        get:
            operationId: Detail
            responses:
                '200':
                    description: Ok
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/User'
            security: []
            parameters:
                -
                    in: path
                    name: id
                    required: true
                    schema:
                        type: string
    /users:
        get:
            operationId: List
            responses:
                '200':
                    description: Ok
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: '#/components/schemas/User'
                                type: array
            security: []
            parameters: []
        post:
            operationId: Create
            responses:
                '200':
                    description: Ok
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/User'
            security: []
            parameters: []
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/UserCreationDTO'
servers:
    -
        url: /
